{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "app-secret-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "output-exporting-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "output-exporting-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "output-exporting-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "output-exporting-crypt-credentials-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "new-validation-process"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_output_exporting.secretName }}
      type: Opaque
      data:
        - objectName: "new-validation-process"
          key: new-validation-process
        - objectName: "output-exporting-crypt-credentials-key"
          key: output-exporting-crypt-credentials-key
        - objectName: "output-exporting-db-user"
          key: output-exporting-db-user
        - objectName: "output-exporting-db-password"
          key: output-exporting-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "output-exporting-db"
          key: output-exporting-db
        - objectName: "app-secret-key"
          key: app-secret-key
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
{{- end }}
