secrets:
  deps_output_exporting:
    secretName: deps-output-exporting
  app_secret_key:
    secretName: app-secret-key
  output_exporting_database:
    secretName: output-exporting-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  redis_password:
    secretName: redis-password
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

output_exporting:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-output-exporting"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

output_exporting_consumer:
  replicaCount: 1
  image:
    path: '/deps-dev-x01/deps-output-exporting'
    pullPolicy: IfNotPresent
    tag: ''
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

output_exporting_settings:
  ENV: dev

  DATABASE_PORT: '5432'
  DATABASE_DRIVER: psycopg2
  DATABASE_DIALECT: postgresql
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

  AUTH_VERIFY_SSL: false

  LOG_LEVEL: "INFO"
  DOCUMENTATION_ENABLED: "true"

  RABBITMQ_TLS_ENABLED: false

  KAFKA_GROUP_ID: output-exporting
  KAFKA_AUTO_OFFSET_RESET: earliest
  KAFKA_SECURITY_ENABLED: false

  FILE_STORAGE_URL: 'http://file-storage-nginx:8000'
  EXTRACTION_URL: 'http://extraction:8000'
  DOCUMENT_TYPE_URL: 'http://document-type:8000'
  DOCUMENT_URL: 'http://backend:8000'
  UNIFIER_URL: 'http://unifier:8000'
  VALIDATION_URL: 'http://validation:8005'
  HIGH_SPARROW_URL: 'http://high-sparrow:8000'
  PARSING_URL: 'http://parsing:8000'
  PROMPTER_URL: 'http://prompter:8000'

  ONE_DRIVE_SCOPES: '["https://graph.microsoft.com/.default"]'
  ONE_DRIVE_BASE_URL: 'https://graph.microsoft.com/v1.0'
  ONE_DRIVE_AUTHORITY_PREFIX: 'https://login.microsoftonline.com'

  SALESFORCE_BASE_URL: 'https://my-domain-name.my.salesforce.com'
  SALESFORCE_AUTH_ENDPOINT: '/services/oauth2/token'
  SALESFORCE_UPLOAD_ENDPOINT: '/services/data/v60.0/sobjects/ContentVersion'

  KVS_OUTPUT_ENABLED: false

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic'
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-output-exporting
  EXPORTER_TYPE: azure

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-output-exporting
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

output_exporting_vault_enabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db-password
  - name: CRYPT_CREDENTIALS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-crypt-credentials-key
  - name: NEW_VALIDATION_PROCESS
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: new-validation-process

output_exporting_vault_disabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: password
  - name: CRYPT_CREDENTIALS_KEY
    valueFrom:
      secretKeyRef:
        name: crypt-credentials-key
        key: output-exporting-crypt-credentials-key
  - name: NEW_VALIDATION_PROCESS
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: new-validation-process

output_exporting_consumer_vault_enabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-db-password
  - name: CRYPT_CREDENTIALS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: output-exporting-crypt-credentials-key
  - name: NEW_VALIDATION_PROCESS
    valueFrom:
      secretKeyRef:
        name: deps-output-exporting
        key: new-validation-process

output_exporting_consumer_vault_disabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secret-key
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: output-exporting-database
        key: password
  - name: CRYPT_CREDENTIALS_KEY
    valueFrom:
      secretKeyRef:
        name: crypt-credentials-key
        key: output-exporting-crypt-credentials-key
  - name: NEW_VALIDATION_PROCESS
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: new-validation-process
