apiVersion: v1
kind: ConfigMap
metadata:
  name: output-exporting-configmap
  labels:
    {{- include "deps-output-exporting.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.output_exporting_settings.ENV }}
  DATABASE_PORT: '{{ .Values.output_exporting_settings.DATABASE_PORT }}'
  DATABASE_DIALECT: '{{ .Values.output_exporting_settings.DATABASE_DIALECT }}'
  DATABASE_DRIVER: '{{ .Values.output_exporting_settings.DATABASE_DRIVER }}'
  DATABASE_REQUIRE_SECURE_TRANSPORT: '{{ .Values.output_exporting_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}'

  {{- if .Values.output_exporting_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
  DATABASE_SSLKEY: {{ .Values.migration_settings.DATABASE_SSLKEY_PATH }}
  DATABASE_SSLCERT: {{ .Values.migration_settings.DATABASE_SSLCERT_PATH }}
  DATABASE_SSLROOTCERT: {{ .Values.migration_settings.DATABASE_SSLROOTCERT_PATH }}
  {{- end }}

  AUTH_VERIFY_SSL: '{{ .Values.output_exporting_settings.AUTH_VERIFY_SSL }}'

  LOG_LEVEL: '{{ .Values.output_exporting_settings.LOG_LEVEL }}'
  DOCUMENTATION_ENABLED: '{{ .Values.output_exporting_settings.DOCUMENTATION_ENABLED }}'

  KAFKA_GROUP_ID: '{{ .Values.output_exporting_settings.KAFKA_GROUP_ID }}'
  KAFKA_AUTO_OFFSET_RESET: '{{ .Values.output_exporting_settings.KAFKA_AUTO_OFFSET_RESET }}'

  {{ if .Values.output_exporting_settings.RABBITMQ_TLS_ENABLED }}
  RABBITMQ_TLS_HOST: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_HOST }}'
  RABBITMQ_TLS_PORT: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_PORT }}'
  RABBITMQ_TLS_USER: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_USER }}'
  RABBITMQ_TLS_VHOST: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_VHOST }}'
  RABBITMQ_TLS_SUBJECT: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_SUBJECT }}'
  RABBITMQ_TLS_CA_CERT: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_CA_CERT }}'
  RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_CLIENT_CERT }}'
  RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.output_exporting_settings.RABBITMQ_TLS_CLIENT_KEY }}'
  {{ end }}

  {{ if .Values.output_exporting_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.output_exporting_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.output_exporting_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}

  FILE_STORAGE_URL: '{{ .Values.output_exporting_settings.FILE_STORAGE_URL }}'
  EXTRACTION_URL: '{{ .Values.output_exporting_settings.EXTRACTION_URL }}'
  DOCUMENT_TYPE_URL: '{{ .Values.output_exporting_settings.DOCUMENT_TYPE_URL }}'
  DOCUMENT_URL: '{{ .Values.output_exporting_settings.DOCUMENT_URL }}'
  UNIFIER_URL: '{{ .Values.output_exporting_settings.UNIFIER_URL }}'
  VALIDATION_URL: '{{ .Values.output_exporting_settings.VALIDATION_URL }}'
  HIGH_SPARROW_URL: '{{ .Values.output_exporting_settings.HIGH_SPARROW_URL }}'
  PARSING_URL: '{{ .Values.output_exporting_settings.PARSING_URL }}'
  PROMPTER_URL: '{{ .Values.output_exporting_settings.PROMPTER_URL }}'

  ONE_DRIVE_SCOPES: '{{ .Values.output_exporting_settings.ONE_DRIVE_SCOPES }}'
  ONE_DRIVE_BASE_URL: '{{ .Values.output_exporting_settings.ONE_DRIVE_BASE_URL }}'
  ONE_DRIVE_AUTHORITY_PREFIX: '{{ .Values.output_exporting_settings.ONE_DRIVE_AUTHORITY_PREFIX }}'

  SALESFORCE_BASE_URL: '{{ .Values.output_exporting_settings.SALESFORCE_BASE_URL }}'
  SALESFORCE_AUTH_ENDPOINT: '{{ .Values.output_exporting_settings.SALESFORCE_AUTH_ENDPOINT }}'
  SALESFORCE_UPLOAD_ENDPOINT: '{{ .Values.output_exporting_settings.SALESFORCE_UPLOAD_ENDPOINT }}'

  KVS_OUTPUT_ENABLED: '{{ .Values.output_exporting_settings.KVS_OUTPUT_ENABLED }}'

  {{ if .Values.output_exporting_settings.message_broker_asb_without_manage_permission }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.output_exporting_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  ASB_TOPIC_NAME: '{{ .Values.output_exporting_settings.ASB_TOPIC_NAME }}'

  # Telemetry
  INSTRUMENTATION_ENABLED: '{{ .Values.output_exporting_settings.INSTRUMENTATION_ENABLED }}'
  SERVICE_NAME: '{{ .Values.output_exporting_settings.SERVICE_NAME }}'
  EXPORTER_TYPE: '{{ .Values.output_exporting_settings.EXPORTER_TYPE }}'
