output_exporting:
  image:
    path: "/deps-platform/deps-output-exporting"
  resources: {}

output_exporting_settings:
  ENV: demo

  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

output_exporting_consumer:
  image:
    path: "/deps-platform/deps-output-exporting"

migrator:
  image:
    path: "/deps-platform/deps-output-exporting-migrator"

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-demo'
  roleName: 'k8s-demo'
  vaultKubernetesMountPath: 'kubernetes-demo'

service_account:
  serviceAccountName: 'deps-demo'
